### ISSUE TITLE
Feat: Dropdown 컴포넌트 구현

### ISSUE THREAD

**Issue by prayinforrain** [c-h-w-h/cds#23]
## 💎 개발할 기능

- [ ] Figma 디자인
- [ ] `select` 태그에 해당하는 `Dropdown` 컴포넌트 구현
  - [ ] 좌측, 우측 정렬; align
  - [ ] 상, 하, 좌, 우 어디로 펼칠지??; direction
- [ ] `option` 태그에 해당하는 `DropdownItem` 컴포넌트 구현

## 📖 참고 사항

23일 저녁부터 할게요..  
그런데 사실 select 태그 자체가 주로 form에 사용되는 요소라서 common에 분류하는게 맞는지 좀 의문이긴 해요

### 02/23 수정
![image](https://user-images.githubusercontent.com/46566891/220965762-5effb9a3-a87c-42c8-a40d-20918aae2528.png)  
![image](https://user-images.githubusercontent.com/46566891/220965551-7ed9cee9-be8f-4e4d-91b3-9c8d05fb9b80.png)
초안인데.. GitHub의 드롭다운을 참고했어요.
'대충 이런 느낌이려나?' 하고 배치만 봤는데, 사실 깃헙의 드롭다운은 워낙 형식이 다채로워서, 아예 레이아웃 요소처럼 option 틀만 두고 그런갑다 할까 고민했는데 일단 형식은 고정하기로 했어요.  
나중에 `optgroup` 태그같은걸로 섹션도 나눌 수 있게 하고 싶은데 그건 당장은 안하기로 했어요.  
사실 디자인 이런게 뭐 중요하겠어요? 우선 드롭다운이 뜨게 하는 로직이 중요하지.. 하는 마인드에요  
  
일단 `form`에 들어가는 `select` 태그만 고려하고, 세영님이 말씀하신 메뉴로서의 드롭다운은 추가 수정으로 구현할 계획이에요.
  
그리고 깃허브 드롭다운 구현되있는거 신기하네요.. `details / summary`로 구현되어 있어요

**Comment by se030** [comment]
navbar 등에서 드롭다운에서 하위 메뉴를 선택하는 경우에도 사용할 수 있을 것 같은데 어때요?

지금 보니까 많이 허접한데 도훈님이랑 비슷한거 만들어본 적 있어요. [이 영상](https://www.youtube.com/watch?v=fR8tsJ2r7Eg) 엄청 좋아요 ..👍🏻
https://saber-ash-4ab.notion.site/Compound-Pattern-69bacacc37db4556bcc20ed6d402b2c8

**Comment by prayinforrain** [comment]
> navbar 등에서 드롭다운에서 하위 메뉴를 선택하는 경우에도 사용할 수 있을 것 같은데 어때요?
> 
> 지금 보니까 많이 허접한데 도훈님이랑 비슷한거 만들어본 적 있어요. [이 영상](https://www.youtube.com/watch?v=fR8tsJ2r7Eg) 엄청 좋아요 ..👍🏻 https://saber-ash-4ab.notion.site/Compound-Pattern-69bacacc37db4556bcc20ed6d402b2c8

처음에 계속 드롭다운 메뉴도 고민했는데요, 둘 사이에 일관성 있는 디자인을 타협 볼 수 있을까 아직 결론을 못내리고 있어요. 아마 옵션으로 선택된 옵션을 보여주는 부분을 어떤 버튼 형태로 고정할 수 있게 하거나.. 그런 식으로 하면 될 것 같아요. 머릿속으로 상상만 한거라 실제 구현할 때 어떨지는 봐야겠지만요..
