### ISSUE TITLE
Config: CI Action 추가

### ISSUE THREAD

**Issue by se030** [c-h-w-h/cds#38]
## 🛠️ 작업사항

- [x] CI Action이 필요해요.

- https://github.com/c-h-w-h/cds/pull/31 PR이 머지되면서 main 브랜치가 에러 있는 상태가 됐어요.
- https://github.com/c-h-w-h/cds/pull/27 에서 Flexbox props가 변경되었는데 #31에는 변경 전 Flexbox로 작업한 내역이 들어가있어서 에러가 발생했어요.
<img width="769" alt="image" src="https://user-images.githubusercontent.com/63814960/221903786-90575222-5083-4e52-b640-4f40b0f98428.png">

- 이런 브랜치룰이 설정되어 있지만 작성된 CI가 없어서 적용이 안되고 있다고 합니다.

**Comment by prayinforrain** [comment]
저요!!!!!!제가할래요!!!!!!!!!

**Comment by prayinforrain** [comment]
![image](https://user-images.githubusercontent.com/46566891/222030295-1075746d-2446-4691-ad76-b3b9ebc43186.png)  
머지하고 브랜치 룰 설정했어요!  
이슈 닫겠습니다~~
