### ISSUE TITLE
Config: 자동 리뷰어 추가 설정하기

### ISSUE THREAD

**Issue by dohun31** [c-h-w-h/cds#45]
## 🛠️ 작업사항

- 리뷰어를 따로 안달아서 새로운 PR이 올라왔는지 매번 레포에 들어와서 확인을 해야해요.
- 그래서 올라오는 PR에 원하는 분들 자동으로 리뷰어 추가할 수 있도록 설정해요.
- 일단 저 등록할건데 따로 원하시는 분들 알려주세요 ~

- [x] 자동으로 리뷰어 등록되게 설정하기

**Comment by se030** [comment]
저도 해주세요 ~
