### ISSUE TITLE
Feat: Carousel 컴포넌트 구현

### ISSUE THREAD

**Issue by leesunmin1231** [c-h-w-h/cds#60]
## 💎 개발할 기능

- [x] Carousel 컴포넌트를 구현합니다.

## 📖 참고 사항
https://uxplanet.org/designing-a-user-friendly-homepage-carousel-f664c9f2b50e#.7yps7ddd7
https://web.dev/i18n/ko/carousel-best-practices/
https://fe-developers.kakaoent.com/2023/230119-scroll-snap/
위 아티클 참고해서 구현해볼 예정입니다

**Comment by prayinforrain** [comment]
https://github.com/iamdustan/smoothscroll/issues/28
`scroll-behavior: smooth` 관련해서 브라우저 버그가 있어요.  
현빈님하고 선민님하고 열심히 머리를 맞대서 해결했는데 레퍼런스 기록차 남겨요 ㅎㅎ..  
여러가지 문제가 있는데.. scrollIntoView를 setTimeout으로 감싼 것도 그 중 하나에요. 이러지 않으면 크롬 기준 양 쪽 끝 카드로 스크롤이 불가능해요.
