### ISSUE TITLE
Config: 패키지 배포

### ISSUE THREAD

**Issue by se030** [c-h-w-h/cds#76]
## 🛠️ 작업사항

- [ ] 작업한 컴포넌트들을 패키지로 배포합니다.

**Comment by iyu88** [comment]
작성해뒀던 package.json이 도움이 될까 하여 올려둘게요.

```
{
  "name": "@cds-ui/react",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "description": "headless react UI component", // 수정해주세요!
  "main": "main.ts",
  "repository": {
    "type": "git",
    "url": "https://github.com/c-h-w-h/cds"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/c-h-w-h/cds/issues",
    "email":  // 누군가의 이메일 
  },
  "homepage": "https://github.com/c-h-w-h/cds",
  "keywords": [
    "react",
    "design system",
    "headless ui",
    "components"
  ],
  "contributors": [
    "Hyunbin Lee <iyu88@naver.com> (https://iyu88.github.io/)",
    "se <se030.kim@gmail.com> (https://velog.io/@se030)",
    "이우재 <prayinforrain@naver.com> (https://prayinforrain.github.io/)",
    "leesunmin1231 <polarlsm1231@gmail.com> (https://polarmin.tistory.com/)",
    "dohun <dohun31@naver.com> (https://dohun31.tistory.com/)"
  ],
}
```

`name`은 라이브러리 찾아보면서 안겹치고 그럴싸한(?) 이름으로 했는데 다른 이름도 좋아요.
`contributors`에는 깃허브 사용자 이름 / 이메일 / 개인 블로그 링크 순서로 넣어두었습니다.

**Comment by se030** [comment]
> 작성해뒀던 package.json이 도움이 될까 하여 올려둘게요.
> 
> ```
> {
>   "name": "@cds-ui/react",
>   "private": true,
>   "version": "1.0.0",
>   "type": "module",
>   "description": "headless react UI component", // 수정해주세요!
>   "main": "main.ts",
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/c-h-w-h/cds"
>   },
>   "license": "MIT",
>   "bugs": {
>     "url": "https://github.com/c-h-w-h/cds/issues",
>     "email":  // 누군가의 이메일 
>   },
>   "homepage": "https://github.com/c-h-w-h/cds",
>   "keywords": [
>     "react",
>     "design system",
>     "headless ui",
>     "components"
>   ],
>   "contributors": [
>     "Hyunbin Lee <iyu88@naver.com> (https://iyu88.github.io/)",
>     "se <se030.kim@gmail.com> (https://velog.io/@se030)",
>     "이우재 <prayinforrain@naver.com> (https://prayinforrain.github.io/)",
>     "leesunmin1231 <polarlsm1231@gmail.com> (https://polarmin.tistory.com/)",
>     "dohun <dohun31@naver.com> (https://dohun31.tistory.com/)"
>   ],
> }
> ```
> 
> `name`은 라이브러리 찾아보면서 안겹치고 그럴싸한(?) 이름으로 했는데 다른 이름도 좋아요. `contributors`에는 깃허브 사용자 이름 / 이메일 / 개인 블로그 링크 순서로 넣어두었습니다.

감사해요!
안그래도 패키지 이름이나 설명 같은건 얘기해보고 정해야 할 것 같아서 개인 계정으로 테스트 배포 해두려고 했는데 ㅋㅋㅋㅋ 저희 registry 만들까요 ^^

**Comment by se030** [comment]
4월 3일 @chwh/cds npm 데뷔 . . . .
