### ISSUE TITLE
Docs: 컴포넌트 스토리 설명 초안 정리

### ISSUE THREAD

**Issue by iyu88** [c-h-w-h/cds#79]
## 📝 문서 작업 사항

- [x] 각 컴포넌트의 스토리에 표시할 설명에 대한 문서 작업을 진행합니다. 
  - 다음 컴포넌트들은 진행하지 않습니다. 
  - Select, RadioButton, Modal, Input

**Comment by se030** [comment]
Badge 도 추가해주실 수 있을까요 ..!ㅎㅎ 인터페이스가 좀 바뀔지 몰라서요 😅
